/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programdata;

/**
 *
 * @author Owner
 */
public class CashierMain extends javax.swing.JFrame {

    /**
     * Creates new form CashierMain
     */
    public CashierMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderList = new javax.swing.JTable();
        Search = new javax.swing.JTextField();
        Go = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 400));
        setPreferredSize(new java.awt.Dimension(640, 400));
        getContentPane().setLayout(null);

        RegisterTitle.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        RegisterTitle.setForeground(new java.awt.Color(153, 51, 0));
        RegisterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterTitle.setText("ORDERS");
        getContentPane().add(RegisterTitle);
        RegisterTitle.setBounds(180, 10, 290, 50);

        OrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"lacasa", "Cameron's", "Light", "100", "2", "132000"},
                {"lacasa", "Death Wish", "Medium", "250", "1", "220000"}
            },
            new String [] {
                "Username", "Coffee Beans", "Roast Level", "Nett (gram)", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(OrderList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 590, 120);

        Search.setText("lacasa");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(20, 60, 100, 30);

        Go.setText(">");
        Go.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        getContentPane().add(Go);
        Go.setBounds(120, 60, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Webp.net-resizeimage (7).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_GoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Go;
    public javax.swing.JTable OrderList;
    private javax.swing.JLabel RegisterTitle;
    private javax.swing.JTextField Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
